{% set name = "tfv" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tfv-{{ version }}.tar.gz
  sha256: 37a0b4c8b2ab0594b1e8e91c10dc114483c629ed7ce7e0d6fd7956b910b4ab54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python  >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.19.0
    - matplotlib-base >3.2.2
    - netcdf4 >=1.5.3
    - xarray >=v2022.03.0
    - dask-core >=2022.01.0
    - scipy >=1.6.0
    - tqdm >=4.50.0
    - wheel

test:
  imports:
    - tfv
  commands:
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest
  source_files:
    - tests/
    - tfv/
about:
  home: https://gitlab.com/TUFLOW/tfv
  summary: Post processing tools for TUFLOW FV results
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TUFLOW-Support
    - Mitch3007
    - Aewaterhouse
